@startuml Diagramme de classes

hide empty members
hide empty methods

' Functions definition
    !function $member($type, $name)
    !return $name + " : <color:green>" + $type + "</color>"
    !endfunction

    !function $list($type, $name)
    !return $member("List<" + $type + ">", $name)
    !endfunction

    !function $int($name)
    !return $member(int, $name)
    !endfunction

    !function $void($name)
    !return $member(void, $name)
    !endfunction

' End functions definition

' Classes definitions

    class "World" as w {
        -$int(currentLevelIndex)
        -$list(Level, levels)
    }

    abstract "AbstractCharacter" as ac {
        #$member(Point, position)
        #$int(hp)
        #$int(atk)
        #$int(def)
        +$void("takeDamage(double)")
        +$void("draw(Graphics)")
        +{abstract} $void("attack(AbtractCharacter)")
        +{abstract} $void("move()")
    }

    class "Hero" as h {
        -$int(points)
    }

    interface "KeyAdapter" as ka {
        +$void("keyPressed(KeyEvent)")
        +$void("keyReleased(KeyEvent)")
        +$void("keyTyped(KeyEvent)")

    }

    class "Swordsman" as sm {

    }

    class "Archer" as cra {

    }

    class "Wizard" as wiz {

    }

    class "Enemy" as e {
        +$void("move()")

    }

    class "IA" as ia {
        +$void("move()")
    }

    class "Level" as l {
        -$int(difficulty)
        -$list(Enemy, enemies)
    }
' End of Classes definitions

' Links

    h -up-|> ac
    h -down-> w
    h -left-> ka

    e -up-|> ac
    e --> ia

    sm --|> h

    cra --|> h

    wiz --|> h

    w "1..N" -right-> l

    l "1..N" -right-> e

' End of Links

@enduml